// <auto-generated />
namespace BigStonks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class myMigration11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(myMigration11));
        
        string IMigrationMetadata.Id
        {
            get { return "202101131707394_myMigration11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
